### ISSUE TITLE
Allow search endpoint to take one parameter

### ISSUE THREAD

**Issue by ctcuff** [ctcuff/COP4331SP#10]
Right now the front end will only ever send one value to the search API so we should update the search endpoint to take a single parameter that matches against all fields, for example:
```json
{
    "query": "e@mail.com"
}
```
Could be named `query` or `search` or anything else that makes sense really

**Comment by Armintron** [comment]
Solved as of commit 88e77979b469dd2bf2a8cf7e07be645e0137928b

**Comment by Armintron** [comment]
The front end still needs to change the sent JSON body to reflect the changes to the API
