### ISSUE TITLE
Action Confirmation

### ISSUE THREAD

**Issue by Armintron** [ctcuff/COP4331SP#11]
Users need to have feedback when they add/delete/update/search a contact. This can be done either with a text box, changes in color, a simple check/X mark - however you guys would like.

**Comment by TheAdoxBox** [comment]
Modal pops up for add contact, updating a contact can only be done when selecting a row, and deleting a contact requires confirmation.

**Comment by Armintron** [comment]
By "confirmation", it means that the user needs to have feedback that their action was successful/failed. For instance, when you add a contact currently, nothing changes on the site other than the row being added. The modal should be closed, and maybe a popup from the top with just a green checkmark so the user knows that the addition was successful.

**Comment by Armintron** [comment]
Done per 4024e2a96f6b81d851acfd0372cbfea273be8700
